Fail fast if docker pull fails
Make it known when the docker pull fails if iac cannot be pulled if
the user is not logged in. They will see this error
ERROR: pull access denied for sdcplatform/iacsvc, repository does
not exist or may require 'docker login'